drop table users cascade;
drop table parkings cascade;
drop table spots cascade;
drop table reserved cascade;

create table users(id int generated by default as identity primary key, username varchar, password varchar, bank int);
create table parkings(id int generated by default as identity primary key, address varchar, carLimit int, available int, latitude int, longitude int);
create table spots(id int generated by default as identity primary key, parking_id int references parkings(id), name varchar, available boolean);
create table reserved(user_id int references users(id), parking_id int references parkings(id), spot_id int references spots(id), duration int);

insert into parkings (address, carLimit, available, latitude, longitude) values ('Ryskulova Momyshuly', 8, 8, 255522, 824583);
insert into parkings (address, carLimit, available, latitude, longitude) values ('Abaya Gagarina', 40, 40, 238385, 893859);
insert into parkings (address, carLimit, available, latitude, longitude) values ('Yassaui Esenova', 80, 80, 225489, 828335);
insert into parkings (address, carLimit, available, latitude, longitude) values ('Tole Bi Baitursunova', 30, 30, 253151, 925335);
insert into parkings (address, carLimit, available, latitude, longitude) values ('Saina Shelkina', 35, 35, 195207, 881165);
insert into parkings (address, carLimit, available, latitude, longitude) values ('Khodzhanova Al-Farabi', 100, 100, 207064, 913178);
insert into parkings (address, carLimit, available, latitude, longitude) values ('Saina Shalyapina', 50, 50, 213823, 856009);
insert into parkings (address, carLimit, available, latitude, longitude) values ('Abaya Momyshuly', 95, 95, 217080, 838903);
insert into parkings (address, carLimit, available, latitude, longitude) values ('Saina Al-Farabi', 60, 60, 195165, 881426);


INSERT INTO spots(parking_id, name, available) VALUES (1, 'C1', 'true');
INSERT INTO spots(parking_id, name, available) VALUES (1, 'A2', 'true');
INSERT INTO spots(parking_id, name, available) VALUES (1, 'A3', 'true');

INSERT INTO spots(parking_id, name, available) VALUES (2, 'A4', 'true');
INSERT INTO spots(parking_id, name, available) VALUES (2, 'C5', 'true');
INSERT INTO spots(parking_id, name, available) VALUES (2, 'A6', 'true');

INSERT INTO spots(parking_id, name, available) VALUES (3, 'A7', 'true');
INSERT INTO spots(parking_id, name, available) VALUES (3, 'B8', 'true');
INSERT INTO spots(parking_id, name, available) VALUES (3, 'A9', 'true');

INSERT INTO spots(parking_id, name, available) VALUES (4, 'A10', 'true');
INSERT INTO spots(parking_id, name, available) VALUES (4, 'B11', 'true');
INSERT INTO spots(parking_id, name, available) VALUES (4, 'A12', 'true');

INSERT INTO spots(parking_id, name, available) VALUES (5, 'A13', 'true');
INSERT INTO spots(parking_id, name, available) VALUES (5, 'D14', 'true');
INSERT INTO spots(parking_id, name, available) VALUES (5, 'A15', 'true');

INSERT INTO spots(parking_id, name, available) VALUES (6, 'A16', 'true');
INSERT INTO spots(parking_id, name, available) VALUES (6, 'B17', 'true');
INSERT INTO spots(parking_id, name, available) VALUES (6, 'A18', 'true');

INSERT INTO spots(parking_id, name, available) VALUES (7, 'D19', 'true');
INSERT INTO spots(parking_id, name, available) VALUES (7, 'A20', 'true');


INSERT INTO spots(parking_id, name, available) VALUES (8, 'B19', 'true');
INSERT INTO spots(parking_id, name, available) VALUES (8, 'A20', 'true');
INSERT INTO spots(parking_id, name, available) VALUES (8, 'C19', 'true');
INSERT INTO spots(parking_id, name, available) VALUES (8, 'A20', 'true');
